# Site settings
title: Formozoli Lab
description: This is a try to understand how to use the themes
url: 
baseurl: ''
profilepic: ''
bkimage: ''

author:
  name: 'Sara Cerioli & Andrey Formozov'

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']

include: ["gh-pages"]
