# Site settings
title:  Formozoli Lab
description: Let's try this again
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/jekyll-uno'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Sara & Andrey'
  email: sara.andrey@gmail.com
  twitter_username: blabliblup
  facebook_username: blabliblup
  github_username:  blabliblup
  linkedin_username:  blabliblup

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
include: ["_posts"]
